server:
  port: 8098


spring:
  application:
    name: springtaller5
  h2:
    console:
      settings:
        web-allow-others: false
        trace: false
      path: /h2-console
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    